<?php
/**
 * CitySpendingAnalysisEntity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CitySpendingAnalysisEntity Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CitySpendingAnalysisEntity implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CitySpendingAnalysisEntity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
'city_id' => 'string',
'employee_count' => 'string',
'spend_dollars' => 'string',
'annualized_spend_dollars' => 'string',
'savings_dollars' => 'string',
'annualized_savings_dollars' => 'string',
'payroll_taxes_dollars' => 'string',
'spend_per_employee_dollars' => 'string',
'annualized_spend_per_employee_dollars' => 'string',
'savings_per_employee_dollars' => 'string',
'annualized_savings_per_employee_dollars' => 'string',
'average_alice_income_dollars' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
'city_id' => null,
'employee_count' => null,
'spend_dollars' => null,
'annualized_spend_dollars' => null,
'savings_dollars' => null,
'annualized_savings_dollars' => null,
'payroll_taxes_dollars' => null,
'spend_per_employee_dollars' => null,
'annualized_spend_per_employee_dollars' => null,
'savings_per_employee_dollars' => null,
'annualized_savings_per_employee_dollars' => null,
'average_alice_income_dollars' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
'city_id' => 'city_id',
'employee_count' => 'employee_count',
'spend_dollars' => 'spend_dollars',
'annualized_spend_dollars' => 'annualized_spend_dollars',
'savings_dollars' => 'savings_dollars',
'annualized_savings_dollars' => 'annualized_savings_dollars',
'payroll_taxes_dollars' => 'payroll_taxes_dollars',
'spend_per_employee_dollars' => 'spend_per_employee_dollars',
'annualized_spend_per_employee_dollars' => 'annualized_spend_per_employee_dollars',
'savings_per_employee_dollars' => 'savings_per_employee_dollars',
'annualized_savings_per_employee_dollars' => 'annualized_savings_per_employee_dollars',
'average_alice_income_dollars' => 'average_alice_income_dollars'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
'city_id' => 'setCityId',
'employee_count' => 'setEmployeeCount',
'spend_dollars' => 'setSpendDollars',
'annualized_spend_dollars' => 'setAnnualizedSpendDollars',
'savings_dollars' => 'setSavingsDollars',
'annualized_savings_dollars' => 'setAnnualizedSavingsDollars',
'payroll_taxes_dollars' => 'setPayrollTaxesDollars',
'spend_per_employee_dollars' => 'setSpendPerEmployeeDollars',
'annualized_spend_per_employee_dollars' => 'setAnnualizedSpendPerEmployeeDollars',
'savings_per_employee_dollars' => 'setSavingsPerEmployeeDollars',
'annualized_savings_per_employee_dollars' => 'setAnnualizedSavingsPerEmployeeDollars',
'average_alice_income_dollars' => 'setAverageAliceIncomeDollars'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
'city_id' => 'getCityId',
'employee_count' => 'getEmployeeCount',
'spend_dollars' => 'getSpendDollars',
'annualized_spend_dollars' => 'getAnnualizedSpendDollars',
'savings_dollars' => 'getSavingsDollars',
'annualized_savings_dollars' => 'getAnnualizedSavingsDollars',
'payroll_taxes_dollars' => 'getPayrollTaxesDollars',
'spend_per_employee_dollars' => 'getSpendPerEmployeeDollars',
'annualized_spend_per_employee_dollars' => 'getAnnualizedSpendPerEmployeeDollars',
'savings_per_employee_dollars' => 'getSavingsPerEmployeeDollars',
'annualized_savings_per_employee_dollars' => 'getAnnualizedSavingsPerEmployeeDollars',
'average_alice_income_dollars' => 'getAverageAliceIncomeDollars'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['city_id'] = isset($data['city_id']) ? $data['city_id'] : null;
        $this->container['employee_count'] = isset($data['employee_count']) ? $data['employee_count'] : null;
        $this->container['spend_dollars'] = isset($data['spend_dollars']) ? $data['spend_dollars'] : null;
        $this->container['annualized_spend_dollars'] = isset($data['annualized_spend_dollars']) ? $data['annualized_spend_dollars'] : null;
        $this->container['savings_dollars'] = isset($data['savings_dollars']) ? $data['savings_dollars'] : null;
        $this->container['annualized_savings_dollars'] = isset($data['annualized_savings_dollars']) ? $data['annualized_savings_dollars'] : null;
        $this->container['payroll_taxes_dollars'] = isset($data['payroll_taxes_dollars']) ? $data['payroll_taxes_dollars'] : null;
        $this->container['spend_per_employee_dollars'] = isset($data['spend_per_employee_dollars']) ? $data['spend_per_employee_dollars'] : null;
        $this->container['annualized_spend_per_employee_dollars'] = isset($data['annualized_spend_per_employee_dollars']) ? $data['annualized_spend_per_employee_dollars'] : null;
        $this->container['savings_per_employee_dollars'] = isset($data['savings_per_employee_dollars']) ? $data['savings_per_employee_dollars'] : null;
        $this->container['annualized_savings_per_employee_dollars'] = isset($data['annualized_savings_per_employee_dollars']) ? $data['annualized_savings_per_employee_dollars'] : null;
        $this->container['average_alice_income_dollars'] = isset($data['average_alice_income_dollars']) ? $data['average_alice_income_dollars'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets city_id
     *
     * @return string
     */
    public function getCityId()
    {
        return $this->container['city_id'];
    }

    /**
     * Sets city_id
     *
     * @param string $city_id city_id
     *
     * @return $this
     */
    public function setCityId($city_id)
    {
        $this->container['city_id'] = $city_id;

        return $this;
    }

    /**
     * Gets employee_count
     *
     * @return string
     */
    public function getEmployeeCount()
    {
        return $this->container['employee_count'];
    }

    /**
     * Sets employee_count
     *
     * @param string $employee_count employee_count
     *
     * @return $this
     */
    public function setEmployeeCount($employee_count)
    {
        $this->container['employee_count'] = $employee_count;

        return $this;
    }

    /**
     * Gets spend_dollars
     *
     * @return string
     */
    public function getSpendDollars()
    {
        return $this->container['spend_dollars'];
    }

    /**
     * Sets spend_dollars
     *
     * @param string $spend_dollars spend_dollars
     *
     * @return $this
     */
    public function setSpendDollars($spend_dollars)
    {
        $this->container['spend_dollars'] = $spend_dollars;

        return $this;
    }

    /**
     * Gets annualized_spend_dollars
     *
     * @return string
     */
    public function getAnnualizedSpendDollars()
    {
        return $this->container['annualized_spend_dollars'];
    }

    /**
     * Sets annualized_spend_dollars
     *
     * @param string $annualized_spend_dollars annualized_spend_dollars
     *
     * @return $this
     */
    public function setAnnualizedSpendDollars($annualized_spend_dollars)
    {
        $this->container['annualized_spend_dollars'] = $annualized_spend_dollars;

        return $this;
    }

    /**
     * Gets savings_dollars
     *
     * @return string
     */
    public function getSavingsDollars()
    {
        return $this->container['savings_dollars'];
    }

    /**
     * Sets savings_dollars
     *
     * @param string $savings_dollars savings_dollars
     *
     * @return $this
     */
    public function setSavingsDollars($savings_dollars)
    {
        $this->container['savings_dollars'] = $savings_dollars;

        return $this;
    }

    /**
     * Gets annualized_savings_dollars
     *
     * @return string
     */
    public function getAnnualizedSavingsDollars()
    {
        return $this->container['annualized_savings_dollars'];
    }

    /**
     * Sets annualized_savings_dollars
     *
     * @param string $annualized_savings_dollars annualized_savings_dollars
     *
     * @return $this
     */
    public function setAnnualizedSavingsDollars($annualized_savings_dollars)
    {
        $this->container['annualized_savings_dollars'] = $annualized_savings_dollars;

        return $this;
    }

    /**
     * Gets payroll_taxes_dollars
     *
     * @return string
     */
    public function getPayrollTaxesDollars()
    {
        return $this->container['payroll_taxes_dollars'];
    }

    /**
     * Sets payroll_taxes_dollars
     *
     * @param string $payroll_taxes_dollars payroll_taxes_dollars
     *
     * @return $this
     */
    public function setPayrollTaxesDollars($payroll_taxes_dollars)
    {
        $this->container['payroll_taxes_dollars'] = $payroll_taxes_dollars;

        return $this;
    }

    /**
     * Gets spend_per_employee_dollars
     *
     * @return string
     */
    public function getSpendPerEmployeeDollars()
    {
        return $this->container['spend_per_employee_dollars'];
    }

    /**
     * Sets spend_per_employee_dollars
     *
     * @param string $spend_per_employee_dollars spend_per_employee_dollars
     *
     * @return $this
     */
    public function setSpendPerEmployeeDollars($spend_per_employee_dollars)
    {
        $this->container['spend_per_employee_dollars'] = $spend_per_employee_dollars;

        return $this;
    }

    /**
     * Gets annualized_spend_per_employee_dollars
     *
     * @return string
     */
    public function getAnnualizedSpendPerEmployeeDollars()
    {
        return $this->container['annualized_spend_per_employee_dollars'];
    }

    /**
     * Sets annualized_spend_per_employee_dollars
     *
     * @param string $annualized_spend_per_employee_dollars annualized_spend_per_employee_dollars
     *
     * @return $this
     */
    public function setAnnualizedSpendPerEmployeeDollars($annualized_spend_per_employee_dollars)
    {
        $this->container['annualized_spend_per_employee_dollars'] = $annualized_spend_per_employee_dollars;

        return $this;
    }

    /**
     * Gets savings_per_employee_dollars
     *
     * @return string
     */
    public function getSavingsPerEmployeeDollars()
    {
        return $this->container['savings_per_employee_dollars'];
    }

    /**
     * Sets savings_per_employee_dollars
     *
     * @param string $savings_per_employee_dollars savings_per_employee_dollars
     *
     * @return $this
     */
    public function setSavingsPerEmployeeDollars($savings_per_employee_dollars)
    {
        $this->container['savings_per_employee_dollars'] = $savings_per_employee_dollars;

        return $this;
    }

    /**
     * Gets annualized_savings_per_employee_dollars
     *
     * @return string
     */
    public function getAnnualizedSavingsPerEmployeeDollars()
    {
        return $this->container['annualized_savings_per_employee_dollars'];
    }

    /**
     * Sets annualized_savings_per_employee_dollars
     *
     * @param string $annualized_savings_per_employee_dollars annualized_savings_per_employee_dollars
     *
     * @return $this
     */
    public function setAnnualizedSavingsPerEmployeeDollars($annualized_savings_per_employee_dollars)
    {
        $this->container['annualized_savings_per_employee_dollars'] = $annualized_savings_per_employee_dollars;

        return $this;
    }

    /**
     * Gets average_alice_income_dollars
     *
     * @return string
     */
    public function getAverageAliceIncomeDollars()
    {
        return $this->container['average_alice_income_dollars'];
    }

    /**
     * Sets average_alice_income_dollars
     *
     * @param string $average_alice_income_dollars average_alice_income_dollars
     *
     * @return $this
     */
    public function setAverageAliceIncomeDollars($average_alice_income_dollars)
    {
        $this->container['average_alice_income_dollars'] = $average_alice_income_dollars;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
