<?php
/**
 * EmployerSummaryEntity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EmployerSummaryEntity Class Doc Comment
 *
 * @category Class
 * @description Gives a summary of the employer sufficient to present them in the dashboard view
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmployerSummaryEntity implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EmployerSummaryEntity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
'payroll_system_id' => 'string',
'name' => 'string',
'marketing_friendly_name' => 'string',
'billing_system_connected' => 'bool',
'billing_source' => '\Swagger\Client\Model\BillingSourceEntity',
'payroll_account' => '\Swagger\Client\Model\AccountEntity',
'requires_benefit_bank_account' => 'bool',
'unified_billing' => 'bool',
'signup_date' => '\DateTime',
'invite_code' => 'string',
'enroll_url' => 'string',
'employees' => '\Swagger\Client\Model\EmployeeCollectionSummaryEntity',
'estimated_possible_annual_savings' => '\Swagger\Client\Model\EmployerAnnualSavingsEntity',
'total_savings' => '\Swagger\Client\Model\EmployerTotalSavingsEntity',
'next_pay_period' => '\Swagger\Client\Model\PayPeriodEntity',
'address' => '\Swagger\Client\Model\AddressEntity'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
'payroll_system_id' => null,
'name' => null,
'marketing_friendly_name' => null,
'billing_system_connected' => null,
'billing_source' => null,
'payroll_account' => null,
'requires_benefit_bank_account' => null,
'unified_billing' => null,
'signup_date' => 'date',
'invite_code' => null,
'enroll_url' => null,
'employees' => null,
'estimated_possible_annual_savings' => null,
'total_savings' => null,
'next_pay_period' => null,
'address' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'payroll_system_id' => 'payroll_system_id',
'name' => 'name',
'marketing_friendly_name' => 'marketing_friendly_name',
'billing_system_connected' => 'billing_system_connected',
'billing_source' => 'billing_source',
'payroll_account' => 'payroll_account',
'requires_benefit_bank_account' => 'requires_benefit_bank_account',
'unified_billing' => 'unified_billing',
'signup_date' => 'signup_date',
'invite_code' => 'invite_code',
'enroll_url' => 'enroll_url',
'employees' => 'employees',
'estimated_possible_annual_savings' => 'estimated_possible_annual_savings',
'total_savings' => 'total_savings',
'next_pay_period' => 'next_pay_period',
'address' => 'address'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'payroll_system_id' => 'setPayrollSystemId',
'name' => 'setName',
'marketing_friendly_name' => 'setMarketingFriendlyName',
'billing_system_connected' => 'setBillingSystemConnected',
'billing_source' => 'setBillingSource',
'payroll_account' => 'setPayrollAccount',
'requires_benefit_bank_account' => 'setRequiresBenefitBankAccount',
'unified_billing' => 'setUnifiedBilling',
'signup_date' => 'setSignupDate',
'invite_code' => 'setInviteCode',
'enroll_url' => 'setEnrollUrl',
'employees' => 'setEmployees',
'estimated_possible_annual_savings' => 'setEstimatedPossibleAnnualSavings',
'total_savings' => 'setTotalSavings',
'next_pay_period' => 'setNextPayPeriod',
'address' => 'setAddress'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'payroll_system_id' => 'getPayrollSystemId',
'name' => 'getName',
'marketing_friendly_name' => 'getMarketingFriendlyName',
'billing_system_connected' => 'getBillingSystemConnected',
'billing_source' => 'getBillingSource',
'payroll_account' => 'getPayrollAccount',
'requires_benefit_bank_account' => 'getRequiresBenefitBankAccount',
'unified_billing' => 'getUnifiedBilling',
'signup_date' => 'getSignupDate',
'invite_code' => 'getInviteCode',
'enroll_url' => 'getEnrollUrl',
'employees' => 'getEmployees',
'estimated_possible_annual_savings' => 'getEstimatedPossibleAnnualSavings',
'total_savings' => 'getTotalSavings',
'next_pay_period' => 'getNextPayPeriod',
'address' => 'getAddress'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['payroll_system_id'] = isset($data['payroll_system_id']) ? $data['payroll_system_id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['marketing_friendly_name'] = isset($data['marketing_friendly_name']) ? $data['marketing_friendly_name'] : null;
        $this->container['billing_system_connected'] = isset($data['billing_system_connected']) ? $data['billing_system_connected'] : true;
        $this->container['billing_source'] = isset($data['billing_source']) ? $data['billing_source'] : null;
        $this->container['payroll_account'] = isset($data['payroll_account']) ? $data['payroll_account'] : null;
        $this->container['requires_benefit_bank_account'] = isset($data['requires_benefit_bank_account']) ? $data['requires_benefit_bank_account'] : null;
        $this->container['unified_billing'] = isset($data['unified_billing']) ? $data['unified_billing'] : null;
        $this->container['signup_date'] = isset($data['signup_date']) ? $data['signup_date'] : null;
        $this->container['invite_code'] = isset($data['invite_code']) ? $data['invite_code'] : 'acme420';
        $this->container['enroll_url'] = isset($data['enroll_url']) ? $data['enroll_url'] : 'https://app.thisisalice.com/enroll/acme420';
        $this->container['employees'] = isset($data['employees']) ? $data['employees'] : null;
        $this->container['estimated_possible_annual_savings'] = isset($data['estimated_possible_annual_savings']) ? $data['estimated_possible_annual_savings'] : null;
        $this->container['total_savings'] = isset($data['total_savings']) ? $data['total_savings'] : null;
        $this->container['next_pay_period'] = isset($data['next_pay_period']) ? $data['next_pay_period'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['payroll_system_id'] === null) {
            $invalidProperties[] = "'payroll_system_id' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['requires_benefit_bank_account'] === null) {
            $invalidProperties[] = "'requires_benefit_bank_account' can't be null";
        }
        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Company ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets payroll_system_id
     *
     * @return string
     */
    public function getPayrollSystemId()
    {
        return $this->container['payroll_system_id'];
    }

    /**
     * Sets payroll_system_id
     *
     * @param string $payroll_system_id Employee ID within the external payroll system
     *
     * @return $this
     */
    public function setPayrollSystemId($payroll_system_id)
    {
        $this->container['payroll_system_id'] = $payroll_system_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Company Name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets marketing_friendly_name
     *
     * @return string
     */
    public function getMarketingFriendlyName()
    {
        return $this->container['marketing_friendly_name'];
    }

    /**
     * Sets marketing_friendly_name
     *
     * @param string $marketing_friendly_name Company Friendly Name
     *
     * @return $this
     */
    public function setMarketingFriendlyName($marketing_friendly_name)
    {
        $this->container['marketing_friendly_name'] = $marketing_friendly_name;

        return $this;
    }

    /**
     * Gets billing_system_connected
     *
     * @return bool
     */
    public function getBillingSystemConnected()
    {
        return $this->container['billing_system_connected'];
    }

    /**
     * Sets billing_system_connected
     *
     * @param bool $billing_system_connected Identifies if the billable can be billed
     *
     * @return $this
     */
    public function setBillingSystemConnected($billing_system_connected)
    {
        $this->container['billing_system_connected'] = $billing_system_connected;

        return $this;
    }

    /**
     * Gets billing_source
     *
     * @return \Swagger\Client\Model\BillingSourceEntity
     */
    public function getBillingSource()
    {
        return $this->container['billing_source'];
    }

    /**
     * Sets billing_source
     *
     * @param \Swagger\Client\Model\BillingSourceEntity $billing_source billing_source
     *
     * @return $this
     */
    public function setBillingSource($billing_source)
    {
        $this->container['billing_source'] = $billing_source;

        return $this;
    }

    /**
     * Gets payroll_account
     *
     * @return \Swagger\Client\Model\AccountEntity
     */
    public function getPayrollAccount()
    {
        return $this->container['payroll_account'];
    }

    /**
     * Sets payroll_account
     *
     * @param \Swagger\Client\Model\AccountEntity $payroll_account payroll_account
     *
     * @return $this
     */
    public function setPayrollAccount($payroll_account)
    {
        $this->container['payroll_account'] = $payroll_account;

        return $this;
    }

    /**
     * Gets requires_benefit_bank_account
     *
     * @return bool
     */
    public function getRequiresBenefitBankAccount()
    {
        return $this->container['requires_benefit_bank_account'];
    }

    /**
     * Sets requires_benefit_bank_account
     *
     * @param bool $requires_benefit_bank_account Whether the organization offers a benefit that requires a bank account, like HFSA or HSA
     *
     * @return $this
     */
    public function setRequiresBenefitBankAccount($requires_benefit_bank_account)
    {
        $this->container['requires_benefit_bank_account'] = $requires_benefit_bank_account;

        return $this;
    }

    /**
     * Gets unified_billing
     *
     * @return bool
     */
    public function getUnifiedBilling()
    {
        return $this->container['unified_billing'];
    }

    /**
     * Sets unified_billing
     *
     * @param bool $unified_billing Unified billing
     *
     * @return $this
     */
    public function setUnifiedBilling($unified_billing)
    {
        $this->container['unified_billing'] = $unified_billing;

        return $this;
    }

    /**
     * Gets signup_date
     *
     * @return \DateTime
     */
    public function getSignupDate()
    {
        return $this->container['signup_date'];
    }

    /**
     * Sets signup_date
     *
     * @param \DateTime $signup_date Date the company signed up
     *
     * @return $this
     */
    public function setSignupDate($signup_date)
    {
        $this->container['signup_date'] = $signup_date;

        return $this;
    }

    /**
     * Gets invite_code
     *
     * @return string
     */
    public function getInviteCode()
    {
        return $this->container['invite_code'];
    }

    /**
     * Sets invite_code
     *
     * @param string $invite_code Invite code
     *
     * @return $this
     */
    public function setInviteCode($invite_code)
    {
        $this->container['invite_code'] = $invite_code;

        return $this;
    }

    /**
     * Gets enroll_url
     *
     * @return string
     */
    public function getEnrollUrl()
    {
        return $this->container['enroll_url'];
    }

    /**
     * Sets enroll_url
     *
     * @param string $enroll_url Enrollment URL for invite code
     *
     * @return $this
     */
    public function setEnrollUrl($enroll_url)
    {
        $this->container['enroll_url'] = $enroll_url;

        return $this;
    }

    /**
     * Gets employees
     *
     * @return \Swagger\Client\Model\EmployeeCollectionSummaryEntity
     */
    public function getEmployees()
    {
        return $this->container['employees'];
    }

    /**
     * Sets employees
     *
     * @param \Swagger\Client\Model\EmployeeCollectionSummaryEntity $employees employees
     *
     * @return $this
     */
    public function setEmployees($employees)
    {
        $this->container['employees'] = $employees;

        return $this;
    }

    /**
     * Gets estimated_possible_annual_savings
     *
     * @return \Swagger\Client\Model\EmployerAnnualSavingsEntity
     */
    public function getEstimatedPossibleAnnualSavings()
    {
        return $this->container['estimated_possible_annual_savings'];
    }

    /**
     * Sets estimated_possible_annual_savings
     *
     * @param \Swagger\Client\Model\EmployerAnnualSavingsEntity $estimated_possible_annual_savings estimated_possible_annual_savings
     *
     * @return $this
     */
    public function setEstimatedPossibleAnnualSavings($estimated_possible_annual_savings)
    {
        $this->container['estimated_possible_annual_savings'] = $estimated_possible_annual_savings;

        return $this;
    }

    /**
     * Gets total_savings
     *
     * @return \Swagger\Client\Model\EmployerTotalSavingsEntity
     */
    public function getTotalSavings()
    {
        return $this->container['total_savings'];
    }

    /**
     * Sets total_savings
     *
     * @param \Swagger\Client\Model\EmployerTotalSavingsEntity $total_savings total_savings
     *
     * @return $this
     */
    public function setTotalSavings($total_savings)
    {
        $this->container['total_savings'] = $total_savings;

        return $this;
    }

    /**
     * Gets next_pay_period
     *
     * @return \Swagger\Client\Model\PayPeriodEntity
     */
    public function getNextPayPeriod()
    {
        return $this->container['next_pay_period'];
    }

    /**
     * Sets next_pay_period
     *
     * @param \Swagger\Client\Model\PayPeriodEntity $next_pay_period next_pay_period
     *
     * @return $this
     */
    public function setNextPayPeriod($next_pay_period)
    {
        $this->container['next_pay_period'] = $next_pay_period;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \Swagger\Client\Model\AddressEntity
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \Swagger\Client\Model\AddressEntity $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
