<?php
/**
 * EmployeeReimbursementClaimEntity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EmployeeReimbursementClaimEntity Class Doc Comment
 *
 * @category Class
 * @description The main use for this endpoint is to add supporting documents to a claim
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmployeeReimbursementClaimEntity implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EmployeeReimbursementClaimEntity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
'approval_status' => 'string',
'claim_documents' => '\Swagger\Client\Model\ClaimDocumentEntity[]',
'reviewed_at' => '\DateTime',
'reviewer_note' => 'string'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
'approval_status' => null,
'claim_documents' => null,
'reviewed_at' => 'date',
'reviewer_note' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'approval_status' => 'approval_status',
'claim_documents' => 'claim_documents',
'reviewed_at' => 'reviewed_at',
'reviewer_note' => 'reviewer_note'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'approval_status' => 'setApprovalStatus',
'claim_documents' => 'setClaimDocuments',
'reviewed_at' => 'setReviewedAt',
'reviewer_note' => 'setReviewerNote'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'approval_status' => 'getApprovalStatus',
'claim_documents' => 'getClaimDocuments',
'reviewed_at' => 'getReviewedAt',
'reviewer_note' => 'getReviewerNote'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const APPROVAL_STATUS_PENDING = 'pending';
const APPROVAL_STATUS_APPROVED = 'approved';
const APPROVAL_STATUS_DENIED = 'denied';
const APPROVAL_STATUS_NOT_REQUIRED = 'not_required';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getApprovalStatusAllowableValues()
    {
        return [
            self::APPROVAL_STATUS_PENDING,
self::APPROVAL_STATUS_APPROVED,
self::APPROVAL_STATUS_DENIED,
self::APPROVAL_STATUS_NOT_REQUIRED,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : 1;
        $this->container['approval_status'] = isset($data['approval_status']) ? $data['approval_status'] : 'pending';
        $this->container['claim_documents'] = isset($data['claim_documents']) ? $data['claim_documents'] : null;
        $this->container['reviewed_at'] = isset($data['reviewed_at']) ? $data['reviewed_at'] : null;
        $this->container['reviewer_note'] = isset($data['reviewer_note']) ? $data['reviewer_note'] : 'Denied reason';
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['approval_status'] === null) {
            $invalidProperties[] = "'approval_status' can't be null";
        }
        $allowedValues = $this->getApprovalStatusAllowableValues();
        if (!is_null($this->container['approval_status']) && !in_array($this->container['approval_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'approval_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets approval_status
     *
     * @return string
     */
    public function getApprovalStatus()
    {
        return $this->container['approval_status'];
    }

    /**
     * Sets approval_status
     *
     * @param string $approval_status Status of approval
     *
     * @return $this
     */
    public function setApprovalStatus($approval_status)
    {
        $allowedValues = $this->getApprovalStatusAllowableValues();
        if (!in_array($approval_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'approval_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['approval_status'] = $approval_status;

        return $this;
    }

    /**
     * Gets claim_documents
     *
     * @return \Swagger\Client\Model\ClaimDocumentEntity[]
     */
    public function getClaimDocuments()
    {
        return $this->container['claim_documents'];
    }

    /**
     * Sets claim_documents
     *
     * @param \Swagger\Client\Model\ClaimDocumentEntity[] $claim_documents Claim document, with image
     *
     * @return $this
     */
    public function setClaimDocuments($claim_documents)
    {
        $this->container['claim_documents'] = $claim_documents;

        return $this;
    }

    /**
     * Gets reviewed_at
     *
     * @return \DateTime
     */
    public function getReviewedAt()
    {
        return $this->container['reviewed_at'];
    }

    /**
     * Sets reviewed_at
     *
     * @param \DateTime $reviewed_at Approval date
     *
     * @return $this
     */
    public function setReviewedAt($reviewed_at)
    {
        $this->container['reviewed_at'] = $reviewed_at;

        return $this;
    }

    /**
     * Gets reviewer_note
     *
     * @return string
     */
    public function getReviewerNote()
    {
        return $this->container['reviewer_note'];
    }

    /**
     * Sets reviewer_note
     *
     * @param string $reviewer_note Approver comment
     *
     * @return $this
     */
    public function setReviewerNote($reviewer_note)
    {
        $this->container['reviewer_note'] = $reviewer_note;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
