<?php
/**
 * EmployeeEntity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * EmployeeEntity Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmployeeEntity implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'EmployeeEntity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'int',
'payroll_system_id' => 'string',
'first_name' => 'string',
'last_name' => 'string',
'account_status' => 'string',
'is_admin_user' => 'bool',
'is_organization_admin' => 'bool',
'onboarding_status' => 'string',
'total_savings_dollars' => 'float',
'employer_name' => 'string',
'employer_id' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => 'int32',
'payroll_system_id' => null,
'first_name' => null,
'last_name' => null,
'account_status' => null,
'is_admin_user' => null,
'is_organization_admin' => null,
'onboarding_status' => null,
'total_savings_dollars' => 'float',
'employer_name' => null,
'employer_id' => 'int32'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
'payroll_system_id' => 'payroll_system_id',
'first_name' => 'first_name',
'last_name' => 'last_name',
'account_status' => 'account_status',
'is_admin_user' => 'is_admin_user',
'is_organization_admin' => 'is_organization_admin',
'onboarding_status' => 'onboarding_status',
'total_savings_dollars' => 'total_savings_dollars',
'employer_name' => 'employer_name',
'employer_id' => 'employer_id'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
'payroll_system_id' => 'setPayrollSystemId',
'first_name' => 'setFirstName',
'last_name' => 'setLastName',
'account_status' => 'setAccountStatus',
'is_admin_user' => 'setIsAdminUser',
'is_organization_admin' => 'setIsOrganizationAdmin',
'onboarding_status' => 'setOnboardingStatus',
'total_savings_dollars' => 'setTotalSavingsDollars',
'employer_name' => 'setEmployerName',
'employer_id' => 'setEmployerId'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
'payroll_system_id' => 'getPayrollSystemId',
'first_name' => 'getFirstName',
'last_name' => 'getLastName',
'account_status' => 'getAccountStatus',
'is_admin_user' => 'getIsAdminUser',
'is_organization_admin' => 'getIsOrganizationAdmin',
'onboarding_status' => 'getOnboardingStatus',
'total_savings_dollars' => 'getTotalSavingsDollars',
'employer_name' => 'getEmployerName',
'employer_id' => 'getEmployerId'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const ACCOUNT_STATUS_ENROLLED = 'enrolled';
const ACCOUNT_STATUS_OPTED_OUT = 'opted_out';
const ACCOUNT_STATUS_NOT_ENROLLED = 'not_enrolled';
const ACCOUNT_STATUS_INELIGIBLE = 'ineligible';
const ACCOUNT_STATUS_TERMINATED = 'terminated';
const ONBOARDING_STATUS_NOT_INVITED = 'not_invited';
const ONBOARDING_STATUS_INVITED = 'invited';
const ONBOARDING_STATUS_NO_NAME = 'no_name';
const ONBOARDING_STATUS_TEL_NOT_VERIFIED = 'tel_not_verified';
const ONBOARDING_STATUS_NO_ACCOUNTS_CONNECTED = 'no_accounts_connected';
const ONBOARDING_STATUS_HEALTHCARE_ENROLLMENT_INCOMPLETE = 'healthcare_enrollment_incomplete';
const ONBOARDING_STATUS_DEPCARE_ENROLLMENT_INCOMPLETE = 'depcare_enrollment_incomplete';
const ONBOARDING_STATUS_NO_SPEND_YET = 'no_spend_yet';
const ONBOARDING_STATUS_ONBOARDED = 'onboarded';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAccountStatusAllowableValues()
    {
        return [
            self::ACCOUNT_STATUS_ENROLLED,
self::ACCOUNT_STATUS_OPTED_OUT,
self::ACCOUNT_STATUS_NOT_ENROLLED,
self::ACCOUNT_STATUS_INELIGIBLE,
self::ACCOUNT_STATUS_TERMINATED,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getOnboardingStatusAllowableValues()
    {
        return [
            self::ONBOARDING_STATUS_NOT_INVITED,
self::ONBOARDING_STATUS_INVITED,
self::ONBOARDING_STATUS_NO_NAME,
self::ONBOARDING_STATUS_TEL_NOT_VERIFIED,
self::ONBOARDING_STATUS_NO_ACCOUNTS_CONNECTED,
self::ONBOARDING_STATUS_HEALTHCARE_ENROLLMENT_INCOMPLETE,
self::ONBOARDING_STATUS_DEPCARE_ENROLLMENT_INCOMPLETE,
self::ONBOARDING_STATUS_NO_SPEND_YET,
self::ONBOARDING_STATUS_ONBOARDED,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['payroll_system_id'] = isset($data['payroll_system_id']) ? $data['payroll_system_id'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['account_status'] = isset($data['account_status']) ? $data['account_status'] : 'not_enrolled';
        $this->container['is_admin_user'] = isset($data['is_admin_user']) ? $data['is_admin_user'] : null;
        $this->container['is_organization_admin'] = isset($data['is_organization_admin']) ? $data['is_organization_admin'] : null;
        $this->container['onboarding_status'] = isset($data['onboarding_status']) ? $data['onboarding_status'] : 'onboarded';
        $this->container['total_savings_dollars'] = isset($data['total_savings_dollars']) ? $data['total_savings_dollars'] : 32.73;
        $this->container['employer_name'] = isset($data['employer_name']) ? $data['employer_name'] : 'Slytherin House';
        $this->container['employer_id'] = isset($data['employer_id']) ? $data['employer_id'] : 42;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['payroll_system_id'] === null) {
            $invalidProperties[] = "'payroll_system_id' can't be null";
        }
        if ($this->container['first_name'] === null) {
            $invalidProperties[] = "'first_name' can't be null";
        }
        if ($this->container['last_name'] === null) {
            $invalidProperties[] = "'last_name' can't be null";
        }
        if ($this->container['account_status'] === null) {
            $invalidProperties[] = "'account_status' can't be null";
        }
        $allowedValues = $this->getAccountStatusAllowableValues();
        if (!is_null($this->container['account_status']) && !in_array($this->container['account_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'account_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['is_admin_user'] === null) {
            $invalidProperties[] = "'is_admin_user' can't be null";
        }
        if ($this->container['is_organization_admin'] === null) {
            $invalidProperties[] = "'is_organization_admin' can't be null";
        }
        if ($this->container['onboarding_status'] === null) {
            $invalidProperties[] = "'onboarding_status' can't be null";
        }
        $allowedValues = $this->getOnboardingStatusAllowableValues();
        if (!is_null($this->container['onboarding_status']) && !in_array($this->container['onboarding_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'onboarding_status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['total_savings_dollars'] === null) {
            $invalidProperties[] = "'total_savings_dollars' can't be null";
        }
        if ($this->container['employer_name'] === null) {
            $invalidProperties[] = "'employer_name' can't be null";
        }
        if ($this->container['employer_id'] === null) {
            $invalidProperties[] = "'employer_id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Employee ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets payroll_system_id
     *
     * @return string
     */
    public function getPayrollSystemId()
    {
        return $this->container['payroll_system_id'];
    }

    /**
     * Sets payroll_system_id
     *
     * @param string $payroll_system_id Employee ID within the external payroll system
     *
     * @return $this
     */
    public function setPayrollSystemId($payroll_system_id)
    {
        $this->container['payroll_system_id'] = $payroll_system_id;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name First Name
     *
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name First Name
     *
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets account_status
     *
     * @return string
     */
    public function getAccountStatus()
    {
        return $this->container['account_status'];
    }

    /**
     * Sets account_status
     *
     * @param string $account_status Status of the account
     *
     * @return $this
     */
    public function setAccountStatus($account_status)
    {
        $allowedValues = $this->getAccountStatusAllowableValues();
        if (!in_array($account_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'account_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['account_status'] = $account_status;

        return $this;
    }

    /**
     * Gets is_admin_user
     *
     * @return bool
     */
    public function getIsAdminUser()
    {
        return $this->container['is_admin_user'];
    }

    /**
     * Sets is_admin_user
     *
     * @param bool $is_admin_user Identifies if employee can administer Employer Account
     *
     * @return $this
     */
    public function setIsAdminUser($is_admin_user)
    {
        $this->container['is_admin_user'] = $is_admin_user;

        return $this;
    }

    /**
     * Gets is_organization_admin
     *
     * @return bool
     */
    public function getIsOrganizationAdmin()
    {
        return $this->container['is_organization_admin'];
    }

    /**
     * Sets is_organization_admin
     *
     * @param bool $is_organization_admin Identifies if employee can administer their organization
     *
     * @return $this
     */
    public function setIsOrganizationAdmin($is_organization_admin)
    {
        $this->container['is_organization_admin'] = $is_organization_admin;

        return $this;
    }

    /**
     * Gets onboarding_status
     *
     * @return string
     */
    public function getOnboardingStatus()
    {
        return $this->container['onboarding_status'];
    }

    /**
     * Sets onboarding_status
     *
     * @param string $onboarding_status Status of onboarding
     *
     * @return $this
     */
    public function setOnboardingStatus($onboarding_status)
    {
        $allowedValues = $this->getOnboardingStatusAllowableValues();
        if (!in_array($onboarding_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'onboarding_status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['onboarding_status'] = $onboarding_status;

        return $this;
    }

    /**
     * Gets total_savings_dollars
     *
     * @return float
     */
    public function getTotalSavingsDollars()
    {
        return $this->container['total_savings_dollars'];
    }

    /**
     * Sets total_savings_dollars
     *
     * @param float $total_savings_dollars Sum of savings to date
     *
     * @return $this
     */
    public function setTotalSavingsDollars($total_savings_dollars)
    {
        $this->container['total_savings_dollars'] = $total_savings_dollars;

        return $this;
    }

    /**
     * Gets employer_name
     *
     * @return string
     */
    public function getEmployerName()
    {
        return $this->container['employer_name'];
    }

    /**
     * Sets employer_name
     *
     * @param string $employer_name Company Name
     *
     * @return $this
     */
    public function setEmployerName($employer_name)
    {
        $this->container['employer_name'] = $employer_name;

        return $this;
    }

    /**
     * Gets employer_id
     *
     * @return int
     */
    public function getEmployerId()
    {
        return $this->container['employer_id'];
    }

    /**
     * Sets employer_id
     *
     * @param int $employer_id Company ID
     *
     * @return $this
     */
    public function setEmployerId($employer_id)
    {
        $this->container['employer_id'] = $employer_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
