<?php
/**
 * PayPeriodMinimalEntity
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PayPeriodMinimalEntity Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PayPeriodMinimalEntity implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PayPeriodMinimalEntity';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'start_date' => '\DateTime',
'end_date' => '\DateTime',
'employee_deductions_dollars' => 'float',
'id' => 'int',
'payroll_system_id' => 'string',
'status' => 'string',
'payday' => '\DateTime',
'employee_reimbursements_dollars' => 'float',
'employer' => '\Swagger\Client\Model\EmployerMinimalEntity'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'start_date' => 'date',
'end_date' => 'date',
'employee_deductions_dollars' => 'float',
'id' => 'int32',
'payroll_system_id' => null,
'status' => null,
'payday' => 'date',
'employee_reimbursements_dollars' => 'float',
'employer' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'start_date' => 'start_date',
'end_date' => 'end_date',
'employee_deductions_dollars' => 'employee_deductions_dollars',
'id' => 'id',
'payroll_system_id' => 'payroll_system_id',
'status' => 'status',
'payday' => 'payday',
'employee_reimbursements_dollars' => 'employee_reimbursements_dollars',
'employer' => 'employer'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'start_date' => 'setStartDate',
'end_date' => 'setEndDate',
'employee_deductions_dollars' => 'setEmployeeDeductionsDollars',
'id' => 'setId',
'payroll_system_id' => 'setPayrollSystemId',
'status' => 'setStatus',
'payday' => 'setPayday',
'employee_reimbursements_dollars' => 'setEmployeeReimbursementsDollars',
'employer' => 'setEmployer'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'start_date' => 'getStartDate',
'end_date' => 'getEndDate',
'employee_deductions_dollars' => 'getEmployeeDeductionsDollars',
'id' => 'getId',
'payroll_system_id' => 'getPayrollSystemId',
'status' => 'getStatus',
'payday' => 'getPayday',
'employee_reimbursements_dollars' => 'getEmployeeReimbursementsDollars',
'employer' => 'getEmployer'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const STATUS_PENDING = 'pending';
const STATUS_PAYROLL_RUN = 'payroll_run';
const STATUS_CONFIRMED = 'confirmed';
const STATUS_INVOICED = 'invoiced';
const STATUS_PAID = 'paid';
const STATUS_PAID_MISMATCH = 'paid_mismatch';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_PENDING,
self::STATUS_PAYROLL_RUN,
self::STATUS_CONFIRMED,
self::STATUS_INVOICED,
self::STATUS_PAID,
self::STATUS_PAID_MISMATCH,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['start_date'] = isset($data['start_date']) ? $data['start_date'] : null;
        $this->container['end_date'] = isset($data['end_date']) ? $data['end_date'] : null;
        $this->container['employee_deductions_dollars'] = isset($data['employee_deductions_dollars']) ? $data['employee_deductions_dollars'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['payroll_system_id'] = isset($data['payroll_system_id']) ? $data['payroll_system_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : 'pending';
        $this->container['payday'] = isset($data['payday']) ? $data['payday'] : null;
        $this->container['employee_reimbursements_dollars'] = isset($data['employee_reimbursements_dollars']) ? $data['employee_reimbursements_dollars'] : null;
        $this->container['employer'] = isset($data['employer']) ? $data['employer'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['start_date'] === null) {
            $invalidProperties[] = "'start_date' can't be null";
        }
        if ($this->container['end_date'] === null) {
            $invalidProperties[] = "'end_date' can't be null";
        }
        if ($this->container['employee_deductions_dollars'] === null) {
            $invalidProperties[] = "'employee_deductions_dollars' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['payroll_system_id'] === null) {
            $invalidProperties[] = "'payroll_system_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['payday'] === null) {
            $invalidProperties[] = "'payday' can't be null";
        }
        if ($this->container['employee_reimbursements_dollars'] === null) {
            $invalidProperties[] = "'employee_reimbursements_dollars' can't be null";
        }
        if ($this->container['employer'] === null) {
            $invalidProperties[] = "'employer' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets start_date
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime $start_date The start date of the period in question
     *
     * @return $this
     */
    public function setStartDate($start_date)
    {
        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param \DateTime $end_date The end date of the period in question
     *
     * @return $this
     */
    public function setEndDate($end_date)
    {
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets employee_deductions_dollars
     *
     * @return float
     */
    public function getEmployeeDeductionsDollars()
    {
        return $this->container['employee_deductions_dollars'];
    }

    /**
     * Sets employee_deductions_dollars
     *
     * @param float $employee_deductions_dollars Total Employee deductions for this period
     *
     * @return $this
     */
    public function setEmployeeDeductionsDollars($employee_deductions_dollars)
    {
        $this->container['employee_deductions_dollars'] = $employee_deductions_dollars;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id Payroll ID
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets payroll_system_id
     *
     * @return string
     */
    public function getPayrollSystemId()
    {
        return $this->container['payroll_system_id'];
    }

    /**
     * Sets payroll_system_id
     *
     * @param string $payroll_system_id Employee ID within the external payroll system
     *
     * @return $this
     */
    public function setPayrollSystemId($payroll_system_id)
    {
        $this->container['payroll_system_id'] = $payroll_system_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status Pay period status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets payday
     *
     * @return \DateTime
     */
    public function getPayday()
    {
        return $this->container['payday'];
    }

    /**
     * Sets payday
     *
     * @param \DateTime $payday The pay day of the period in question
     *
     * @return $this
     */
    public function setPayday($payday)
    {
        $this->container['payday'] = $payday;

        return $this;
    }

    /**
     * Gets employee_reimbursements_dollars
     *
     * @return float
     */
    public function getEmployeeReimbursementsDollars()
    {
        return $this->container['employee_reimbursements_dollars'];
    }

    /**
     * Sets employee_reimbursements_dollars
     *
     * @param float $employee_reimbursements_dollars Total Employee reimbursements for this period
     *
     * @return $this
     */
    public function setEmployeeReimbursementsDollars($employee_reimbursements_dollars)
    {
        $this->container['employee_reimbursements_dollars'] = $employee_reimbursements_dollars;

        return $this;
    }

    /**
     * Gets employer
     *
     * @return \Swagger\Client\Model\EmployerMinimalEntity
     */
    public function getEmployer()
    {
        return $this->container['employer'];
    }

    /**
     * Sets employer
     *
     * @param \Swagger\Client\Model\EmployerMinimalEntity $employer employer
     *
     * @return $this
     */
    public function setEmployer($employer)
    {
        $this->container['employer'] = $employer;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
