<?php
/**
 * AccountManagementStatsEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountManagementStatsEntityTest Class Doc Comment
 *
 * @category    Class
 * @description stats on the state of accounts across Alice
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountManagementStatsEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AccountManagementStatsEntity"
     */
    public function testAccountManagementStatsEntity()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "total_organizations"
     */
    public function testPropertyTotalOrganizations()
    {
    }

    /**
     * Test attribute "total_organizations_billing_connected"
     */
    public function testPropertyTotalOrganizationsBillingConnected()
    {
    }

    /**
     * Test attribute "total_organizations_payroll_connected"
     */
    public function testPropertyTotalOrganizationsPayrollConnected()
    {
    }

    /**
     * Test attribute "total_employers"
     */
    public function testPropertyTotalEmployers()
    {
    }

    /**
     * Test attribute "total_employers_account_manager_engaged"
     */
    public function testPropertyTotalEmployersAccountManagerEngaged()
    {
    }

    /**
     * Test attribute "total_employers_onboarding_completed"
     */
    public function testPropertyTotalEmployersOnboardingCompleted()
    {
    }

    /**
     * Test attribute "total_employers_roster_attained"
     */
    public function testPropertyTotalEmployersRosterAttained()
    {
    }

    /**
     * Test attribute "total_employers_enrollment_started"
     */
    public function testPropertyTotalEmployersEnrollmentStarted()
    {
    }
}
