<?php
/**
 * BankingTransactionEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BankingTransactionEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Standalone transaction creation is intended for cash transactions and cases where the user cannot connect one or more of their cards
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BankingTransactionEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BankingTransactionEntity"
     */
    public function testBankingTransactionEntity()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "amount_dollars"
     */
    public function testPropertyAmountDollars()
    {
    }

    /**
     * Test attribute "pretax_category"
     */
    public function testPropertyPretaxCategory()
    {
    }

    /**
     * Test attribute "estimated_savings_dollars"
     */
    public function testPropertyEstimatedSavingsDollars()
    {
    }

    /**
     * Test attribute "confirmed"
     */
    public function testPropertyConfirmed()
    {
    }

    /**
     * Test attribute "confirmed_at"
     */
    public function testPropertyConfirmedAt()
    {
    }

    /**
     * Test attribute "confirmed_eligible_spend"
     */
    public function testPropertyConfirmedEligibleSpend()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "approval_status"
     */
    public function testPropertyApprovalStatus()
    {
    }

    /**
     * Test attribute "reimbursement_claim"
     */
    public function testPropertyReimbursementClaim()
    {
    }

    /**
     * Test attribute "standalone"
     */
    public function testPropertyStandalone()
    {
    }
}
