<?php
/**
 * ChurnStatsEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChurnStatsEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Monthly stats on churn of Alice members across each employer
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChurnStatsEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChurnStatsEntity"
     */
    public function testChurnStatsEntity()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "alice_churn_count"
     */
    public function testPropertyAliceChurnCount()
    {
    }

    /**
     * Test attribute "alice_customer_churn"
     */
    public function testPropertyAliceCustomerChurn()
    {
    }

    /**
     * Test attribute "removed_from_roster_count"
     */
    public function testPropertyRemovedFromRosterCount()
    {
    }

    /**
     * Test attribute "inactive_user_count"
     */
    public function testPropertyInactiveUserCount()
    {
    }

    /**
     * Test attribute "card_disconnect_count"
     */
    public function testPropertyCardDisconnectCount()
    {
    }

    /**
     * Test attribute "average_churn_by_employer"
     */
    public function testPropertyAverageChurnByEmployer()
    {
    }
}
