<?php
/**
 * DependentCareProgramEnrollmentEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * DependentCareProgramEnrollmentEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Complete enrollment
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DependentCareProgramEnrollmentEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DependentCareProgramEnrollmentEntity"
     */
    public function testDependentCareProgramEnrollmentEntity()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "benefit_type"
     */
    public function testPropertyBenefitType()
    {
    }

    /**
     * Test attribute "estimated_savings_dollars"
     */
    public function testPropertyEstimatedSavingsDollars()
    {
    }

    /**
     * Test attribute "total_spend_dollars"
     */
    public function testPropertyTotalSpendDollars()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "total_deductions"
     */
    public function testPropertyTotalDeductions()
    {
    }

    /**
     * Test attribute "total_deductions_and_balance"
     */
    public function testPropertyTotalDeductionsAndBalance()
    {
    }

    /**
     * Test attribute "yearly_limit"
     */
    public function testPropertyYearlyLimit()
    {
    }

    /**
     * Test attribute "estimated_yearly_limit_savings_dollars"
     */
    public function testPropertyEstimatedYearlyLimitSavingsDollars()
    {
    }

    /**
     * Test attribute "election"
     */
    public function testPropertyElection()
    {
    }

    /**
     * Test attribute "preexisting_deduction"
     */
    public function testPropertyPreexistingDeduction()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "can_change_election"
     */
    public function testPropertyCanChangeElection()
    {
    }

    /**
     * Test attribute "total_reimbursements_in_plan_year"
     */
    public function testPropertyTotalReimbursementsInPlanYear()
    {
    }

    /**
     * Test attribute "employee_providers"
     */
    public function testPropertyEmployeeProviders()
    {
    }

    /**
     * Test attribute "plan_year_start_date"
     */
    public function testPropertyPlanYearStartDate()
    {
    }

    /**
     * Test attribute "plan_year_started"
     */
    public function testPropertyPlanYearStarted()
    {
    }

    /**
     * Test attribute "plan_year_election"
     */
    public function testPropertyPlanYearElection()
    {
    }

    /**
     * Test attribute "plan_year_total_spend_dollars"
     */
    public function testPropertyPlanYearTotalSpendDollars()
    {
    }

    /**
     * Test attribute "plan_year_estimated_savings_dollars"
     */
    public function testPropertyPlanYearEstimatedSavingsDollars()
    {
    }

    /**
     * Test attribute "plan_year"
     */
    public function testPropertyPlanYear()
    {
    }
}
