<?php
/**
 * EmployeeCollectionSummaryEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmployeeCollectionSummaryEntityTest Class Doc Comment
 *
 * @category    Class
 * @description EmployeeCollectionSummaryEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmployeeCollectionSummaryEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmployeeCollectionSummaryEntity"
     */
    public function testEmployeeCollectionSummaryEntity()
    {
    }

    /**
     * Test attribute "employee_count"
     */
    public function testPropertyEmployeeCount()
    {
    }

    /**
     * Test attribute "enrolled"
     */
    public function testPropertyEnrolled()
    {
    }

    /**
     * Test attribute "enrolling"
     */
    public function testPropertyEnrolling()
    {
    }

    /**
     * Test attribute "invited"
     */
    public function testPropertyInvited()
    {
    }

    /**
     * Test attribute "not_invited"
     */
    public function testPropertyNotInvited()
    {
    }

    /**
     * Test attribute "opted_out"
     */
    public function testPropertyOptedOut()
    {
    }

    /**
     * Test attribute "terminated"
     */
    public function testPropertyTerminated()
    {
    }
}
