<?php
/**
 * EmployeeSpendingAnalysisEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmployeeSpendingAnalysisEntityTest Class Doc Comment
 *
 * @category    Class
 * @description EmployeeSpendingAnalysisEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmployeeSpendingAnalysisEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmployeeSpendingAnalysisEntity"
     */
    public function testEmployeeSpendingAnalysisEntity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
    }

    /**
     * Test attribute "days_since_enrollment"
     */
    public function testPropertyDaysSinceEnrollment()
    {
    }

    /**
     * Test attribute "spend_dollars"
     */
    public function testPropertySpendDollars()
    {
    }

    /**
     * Test attribute "annualized_spend_dollars"
     */
    public function testPropertyAnnualizedSpendDollars()
    {
    }

    /**
     * Test attribute "savings_dollars"
     */
    public function testPropertySavingsDollars()
    {
    }

    /**
     * Test attribute "annualized_savings_dollars"
     */
    public function testPropertyAnnualizedSavingsDollars()
    {
    }
}
