<?php
/**
 * EmployerAccountEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EmployerAccountEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Returns information about the employer&#x27;s account, including connected bank account and admin users
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmployerAccountEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "EmployerAccountEntity"
     */
    public function testEmployerAccountEntity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "payroll_system_id"
     */
    public function testPropertyPayrollSystemId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "marketing_friendly_name"
     */
    public function testPropertyMarketingFriendlyName()
    {
    }

    /**
     * Test attribute "admins"
     */
    public function testPropertyAdmins()
    {
    }

    /**
     * Test attribute "billing_system_connected"
     */
    public function testPropertyBillingSystemConnected()
    {
    }

    /**
     * Test attribute "billing_source"
     */
    public function testPropertyBillingSource()
    {
    }

    /**
     * Test attribute "payroll_account"
     */
    public function testPropertyPayrollAccount()
    {
    }

    /**
     * Test attribute "requires_benefit_bank_account"
     */
    public function testPropertyRequiresBenefitBankAccount()
    {
    }

    /**
     * Test attribute "unified_billing"
     */
    public function testPropertyUnifiedBilling()
    {
    }
}
