<?php
/**
 * HSAProgramEnrollmentEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HSAProgramEnrollmentEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Set contribution limit
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HSAProgramEnrollmentEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HSAProgramEnrollmentEntity"
     */
    public function testHSAProgramEnrollmentEntity()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "benefit_type"
     */
    public function testPropertyBenefitType()
    {
    }

    /**
     * Test attribute "estimated_savings_dollars"
     */
    public function testPropertyEstimatedSavingsDollars()
    {
    }

    /**
     * Test attribute "total_spend_dollars"
     */
    public function testPropertyTotalSpendDollars()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "balance"
     */
    public function testPropertyBalance()
    {
    }

    /**
     * Test attribute "total_deductions"
     */
    public function testPropertyTotalDeductions()
    {
    }

    /**
     * Test attribute "total_deductions_and_balance"
     */
    public function testPropertyTotalDeductionsAndBalance()
    {
    }

    /**
     * Test attribute "yearly_limit"
     */
    public function testPropertyYearlyLimit()
    {
    }

    /**
     * Test attribute "estimated_yearly_limit_savings_dollars"
     */
    public function testPropertyEstimatedYearlyLimitSavingsDollars()
    {
    }

    /**
     * Test attribute "election"
     */
    public function testPropertyElection()
    {
    }

    /**
     * Test attribute "preexisting_deduction"
     */
    public function testPropertyPreexistingDeduction()
    {
    }

    /**
     * Test attribute "unnetted_manual_deduction_dollars"
     */
    public function testPropertyUnnettedManualDeductionDollars()
    {
    }

    /**
     * Test attribute "next_deposit_date"
     */
    public function testPropertyNextDepositDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "has_additional_health_coverage"
     */
    public function testPropertyHasAdditionalHealthCoverage()
    {
    }

    /**
     * Test attribute "has_general_purpose_health_fsa"
     */
    public function testPropertyHasGeneralPurposeHealthFsa()
    {
    }

    /**
     * Test attribute "has_general_purpose_hra"
     */
    public function testPropertyHasGeneralPurposeHra()
    {
    }

    /**
     * Test attribute "eligible_for_medicare"
     */
    public function testPropertyEligibleForMedicare()
    {
    }

    /**
     * Test attribute "claimed_as_dependent"
     */
    public function testPropertyClaimedAsDependent()
    {
    }

    /**
     * Test attribute "estimated_yearly_limit"
     */
    public function testPropertyEstimatedYearlyLimit()
    {
    }

    /**
     * Test attribute "permits_manual_deduction"
     */
    public function testPropertyPermitsManualDeduction()
    {
    }

    /**
     * Test attribute "election_per_pay_period_dollars"
     */
    public function testPropertyElectionPerPayPeriodDollars()
    {
    }
}
