<?php
/**
 * MachineLearningPerformanceEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MachineLearningPerformanceEntityTest Class Doc Comment
 *
 * @category    Class
 * @description MachineLearningPerformanceEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MachineLearningPerformanceEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MachineLearningPerformanceEntity"
     */
    public function testMachineLearningPerformanceEntity()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "total_correct"
     */
    public function testPropertyTotalCorrect()
    {
    }

    /**
     * Test attribute "accuracy"
     */
    public function testPropertyAccuracy()
    {
    }

    /**
     * Test attribute "total_reviewed"
     */
    public function testPropertyTotalReviewed()
    {
    }

    /**
     * Test attribute "review_volume"
     */
    public function testPropertyReviewVolume()
    {
    }

    /**
     * Test attribute "incorrect_predicted_below_threshold"
     */
    public function testPropertyIncorrectPredictedBelowThreshold()
    {
    }

    /**
     * Test attribute "incorrect_predicted"
     */
    public function testPropertyIncorrectPredicted()
    {
    }

    /**
     * Test attribute "audit_success_rate"
     */
    public function testPropertyAuditSuccessRate()
    {
    }

    /**
     * Test attribute "classes"
     */
    public function testPropertyClasses()
    {
    }

    /**
     * Test attribute "confusion_matrix"
     */
    public function testPropertyConfusionMatrix()
    {
    }

    /**
     * Test attribute "confusion_matrix_below_threshold"
     */
    public function testPropertyConfusionMatrixBelowThreshold()
    {
    }
}
