<?php
/**
 * OrganizationAdminProfileEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrganizationAdminProfileEntityTest Class Doc Comment
 *
 * @category    Class
 * @description OrganizationAdminProfileEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrganizationAdminProfileEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrganizationAdminProfileEntity"
     */
    public function testOrganizationAdminProfileEntity()
    {
    }

    /**
     * Test attribute "profile_name"
     */
    public function testPropertyProfileName()
    {
    }

    /**
     * Test attribute "num_companies"
     */
    public function testPropertyNumCompanies()
    {
    }

    /**
     * Test attribute "unified_billing"
     */
    public function testPropertyUnifiedBilling()
    {
    }

    /**
     * Test attribute "require_tos_acceptance"
     */
    public function testPropertyRequireTosAcceptance()
    {
    }

    /**
     * Test attribute "tos_accepted_at"
     */
    public function testPropertyTosAcceptedAt()
    {
    }

    /**
     * Test attribute "admin_reports"
     */
    public function testPropertyAdminReports()
    {
    }
}
