<?php
/**
 * OrganizationBenefitEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrganizationBenefitEntityTest Class Doc Comment
 *
 * @category    Class
 * @description OrganizationBenefitEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrganizationBenefitEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OrganizationBenefitEntity"
     */
    public function testOrganizationBenefitEntity()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "benefit_type"
     */
    public function testPropertyBenefitType()
    {
    }

    /**
     * Test attribute "enrollment_start_date"
     */
    public function testPropertyEnrollmentStartDate()
    {
    }

    /**
     * Test attribute "enrollment_end_date"
     */
    public function testPropertyEnrollmentEndDate()
    {
    }

    /**
     * Test attribute "plan_year_start_date"
     */
    public function testPropertyPlanYearStartDate()
    {
    }

    /**
     * Test attribute "plan_year_end_date"
     */
    public function testPropertyPlanYearEndDate()
    {
    }

    /**
     * Test attribute "enrollment_days_remaining"
     */
    public function testPropertyEnrollmentDaysRemaining()
    {
    }

    /**
     * Test attribute "is_fsa"
     */
    public function testPropertyIsFsa()
    {
    }

    /**
     * Test attribute "requires_caf_plan"
     */
    public function testPropertyRequiresCafPlan()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "pretax_category"
     */
    public function testPropertyPretaxCategory()
    {
    }

    /**
     * Test attribute "enrolled_employee_count"
     */
    public function testPropertyEnrolledEmployeeCount()
    {
    }

    /**
     * Test attribute "deductions_per_pay_period_dollars"
     */
    public function testPropertyDeductionsPerPayPeriodDollars()
    {
    }

    /**
     * Test attribute "deductions_this_year_dollars"
     */
    public function testPropertyDeductionsThisYearDollars()
    {
    }

    /**
     * Test attribute "estimated_annual_payroll_tax_savings_dollars"
     */
    public function testPropertyEstimatedAnnualPayrollTaxSavingsDollars()
    {
    }

    /**
     * Test attribute "reimbursements_this_year_dollars"
     */
    public function testPropertyReimbursementsThisYearDollars()
    {
    }
}
