<?php
/**
 * PayPeriodEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PayPeriodEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Returns information for a specific pay period that includes employee benefit deductions and reimbursments
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PayPeriodEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayPeriodEntity"
     */
    public function testPayPeriodEntity()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "employee_count"
     */
    public function testPropertyEmployeeCount()
    {
    }

    /**
     * Test attribute "employee_deductions_dollars"
     */
    public function testPropertyEmployeeDeductionsDollars()
    {
    }

    /**
     * Test attribute "employee_savings_dollars"
     */
    public function testPropertyEmployeeSavingsDollars()
    {
    }

    /**
     * Test attribute "employer_gross_savings_dollars"
     */
    public function testPropertyEmployerGrossSavingsDollars()
    {
    }

    /**
     * Test attribute "employer_fee_dollars"
     */
    public function testPropertyEmployerFeeDollars()
    {
    }

    /**
     * Test attribute "employer_net_savings_dollars"
     */
    public function testPropertyEmployerNetSavingsDollars()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "payroll_system_id"
     */
    public function testPropertyPayrollSystemId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "payday"
     */
    public function testPropertyPayday()
    {
    }

    /**
     * Test attribute "employee_reimbursements_dollars"
     */
    public function testPropertyEmployeeReimbursementsDollars()
    {
    }

    /**
     * Test attribute "invoice_path"
     */
    public function testPropertyInvoicePath()
    {
    }

    /**
     * Test attribute "employer"
     */
    public function testPropertyEmployer()
    {
    }

    /**
     * Test attribute "employees"
     */
    public function testPropertyEmployees()
    {
    }
}
