<?php
/**
 * PayrollConfigEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PayrollConfigEntityTest Class Doc Comment
 *
 * @category    Class
 * @description PayrollConfigEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PayrollConfigEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PayrollConfigEntity"
     */
    public function testPayrollConfigEntity()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "employer"
     */
    public function testPropertyEmployer()
    {
    }

    /**
     * Test attribute "pay_period_type"
     */
    public function testPropertyPayPeriodType()
    {
    }

    /**
     * Test attribute "first_notional_payday"
     */
    public function testPropertyFirstNotionalPayday()
    {
    }

    /**
     * Test attribute "days_paid_in_arrears"
     */
    public function testPropertyDaysPaidInArrears()
    {
    }

    /**
     * Test attribute "deadline_days_before_payday"
     */
    public function testPropertyDeadlineDaysBeforePayday()
    {
    }

    /**
     * Test attribute "periodic_payday"
     */
    public function testPropertyPeriodicPayday()
    {
    }

    /**
     * Test attribute "monthly_payday"
     */
    public function testPropertyMonthlyPayday()
    {
    }

    /**
     * Test attribute "twice_monthly_type"
     */
    public function testPropertyTwiceMonthlyType()
    {
    }

    /**
     * Test attribute "twice_monthly_payday_1"
     */
    public function testPropertyTwiceMonthlyPayday1()
    {
    }

    /**
     * Test attribute "twice_monthly_payday_2"
     */
    public function testPropertyTwiceMonthlyPayday2()
    {
    }
}
