<?php
/**
 * PretaxProgramEnrollmentEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PretaxProgramEnrollmentEntityTest Class Doc Comment
 *
 * @category    Class
 * @description PretaxProgramEnrollmentEntity
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PretaxProgramEnrollmentEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PretaxProgramEnrollmentEntity"
     */
    public function testPretaxProgramEnrollmentEntity()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "benefit_type"
     */
    public function testPropertyBenefitType()
    {
    }

    /**
     * Test attribute "estimated_savings_dollars"
     */
    public function testPropertyEstimatedSavingsDollars()
    {
    }

    /**
     * Test attribute "total_spend_dollars"
     */
    public function testPropertyTotalSpendDollars()
    {
    }
}
