<?php
/**
 * PreviousYearSummaryEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PreviousYearSummaryEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Previous year summary
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PreviousYearSummaryEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PreviousYearSummaryEntity"
     */
    public function testPreviousYearSummaryEntity()
    {
    }

    /**
     * Test attribute "enrolled_in_previous_year"
     */
    public function testPropertyEnrolledInPreviousYear()
    {
    }

    /**
     * Test attribute "previous_year"
     */
    public function testPropertyPreviousYear()
    {
    }

    /**
     * Test attribute "total_contributions"
     */
    public function testPropertyTotalContributions()
    {
    }

    /**
     * Test attribute "amount_remaining"
     */
    public function testPropertyAmountRemaining()
    {
    }

    /**
     * Test attribute "contribution_days_remaining"
     */
    public function testPropertyContributionDaysRemaining()
    {
    }

    /**
     * Test attribute "top_up_start_date"
     */
    public function testPropertyTopUpStartDate()
    {
    }

    /**
     * Test attribute "top_up_end_date"
     */
    public function testPropertyTopUpEndDate()
    {
    }
}
