<?php
/**
 * ProviderEntityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ProviderEntityTest Class Doc Comment
 *
 * @category    Class
 * @description Verifies access token and returns associated dependent care provider
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProviderEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProviderEntity"
     */
    public function testProviderEntity()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "tel"
     */
    public function testPropertyTel()
    {
    }

    /**
     * Test attribute "tax_identification_number"
     */
    public function testPropertyTaxIdentificationNumber()
    {
    }

    /**
     * Test attribute "is_individual"
     */
    public function testPropertyIsIndividual()
    {
    }

    /**
     * Test attribute "is_ssn"
     */
    public function testPropertyIsSsn()
    {
    }

    /**
     * Test attribute "over_eighteen"
     */
    public function testPropertyOverEighteen()
    {
    }

    /**
     * Test attribute "is_tax_exempt"
     */
    public function testPropertyIsTaxExempt()
    {
    }

    /**
     * Test attribute "signatory_name"
     */
    public function testPropertySignatoryName()
    {
    }

    /**
     * Test attribute "employee_name"
     */
    public function testPropertyEmployeeName()
    {
    }

    /**
     * Test attribute "documents"
     */
    public function testPropertyDocuments()
    {
    }
}
