<?php
/**
 * PayrollApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Alice Payroll Provider API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.7
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * PayrollApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PayrollApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getV1PayrollCompanies
     *
     * Companies list.
     *
     */
    public function testGetV1PayrollCompanies()
    {
    }

    /**
     * Test case for getV1PayrollCompaniesCafeteriaPlan
     *
     * Return Cafeteria plan HTML for Square.
     *
     */
    public function testGetV1PayrollCompaniesCafeteriaPlan()
    {
    }

    /**
     * Test case for getV1PayrollCompaniesCompanyId
     *
     * Company details.
     *
     */
    public function testGetV1PayrollCompaniesCompanyId()
    {
    }

    /**
     * Test case for getV1PayrollCompaniesTos
     *
     * Return HTML TOS for Square.
     *
     */
    public function testGetV1PayrollCompaniesTos()
    {
    }

    /**
     * Test case for getV1PayrollPayPeriods
     *
     * Pay periods list.
     *
     */
    public function testGetV1PayrollPayPeriods()
    {
    }

    /**
     * Test case for getV1PayrollPayPeriodsId
     *
     * Pay period details.
     *
     */
    public function testGetV1PayrollPayPeriodsId()
    {
    }

    /**
     * Test case for postV1PayrollCompaniesCompanyIdEmployeesEmployeeIdSessions
     *
     * Create single-use login token.
     *
     */
    public function testPostV1PayrollCompaniesCompanyIdEmployeesEmployeeIdSessions()
    {
    }

    /**
     * Test case for postV1PayrollCompaniesCompanyIdSessions
     *
     * Create single-use login token.
     *
     */
    public function testPostV1PayrollCompaniesCompanyIdSessions()
    {
    }

    /**
     * Test case for postV1PayrollCompaniesOauthSignup
     *
     * Signs up a new Square company.
     *
     */
    public function testPostV1PayrollCompaniesOauthSignup()
    {
    }

    /**
     * Test case for postV1PayrollEvents
     *
     * webhook for payroll companies to push events to us.
     *
     */
    public function testPostV1PayrollEvents()
    {
    }
}
